{
 "title": "Benchmarks",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Certificate reception",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(certificate_received_from_api[$__interval])",
     "legendFormat": "API {{pod}}"
    },
    {
     "expr": "irate(certificate_received_from_gossip[$__interval])",
     "legendFormat": "Gossip {{pod}}"
    }
   ]
  },
  { "title": "Storage layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Command channel at capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(storage_command_channel_capacity[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pending existance latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(storage_pending_certificate_existance_latency_bucket[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "P2P layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "P2P Channel at capacity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "irate(p2p_event_stream_capacity[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Message received",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "irate(echo_message_count[$__interval])",
     "legendFormat": "Echo {{pod}}"
    },
    {
     "expr": "irate(ready_message_count[$__interval])",
     "legendFormat": "Ready {{pod}}"
    },
    {
     "expr": "irate(gossip_message_count[$__interval])",
     "legendFormat": "Gossip {{pod}}"
    }
   ]
  },
  {
   "title": "Gossip message sent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(gossipsub_message_sent_count)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gossip message sent",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(p2p_gossip_batch_size_bucket[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Double Echo - external", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Command channel capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "irate(double_echo_command_channel_capacity[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Double Echo - internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Double echo - Buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "double_echo_current_buffer_size",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Double Echo Buffer at capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "irate(double_echo_buffer_capacity[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Double echo - Buffered messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "double_echo_buffered_message_count",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Double echo - Buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "double_echo_current_buffer_size",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}