name: Contracts - Build

on:
  push:
    branches: 'feat/TP-888'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest-16-core
    defaults:
      run:
        working-directory: ./contracts/

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./contracts/package-lock.json

      - run: npm ci
      - run: npm run build
