name: Sequencer Topos Core Contract interaction test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  sequencer-contracts-e2e:
    runs-on: ubuntu-latest-16-core
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: topos-protocol
          repo: e2e-tests
          github_token: ${{ secrets.ROBOT_PAT_TRIGGER_E2E_WORKFLOWS }}
          workflow_file_name: topos:sequencer-contracts.yml
          ref: main
          wait_interval: 60
          client_payload: '{ "topos-ref": "${{ github.head_ref }}" }'
