name: Topos - Build and host documentation on GH pages
on:
  push:
    branches:
      - feat/TP-888

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    - uses: ./.github/actions/install-rust
      with:
        toolchain: nightly
        AWS_ACCESS_KEY_ID: ${{ secrets.ROBOT_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ROBOT_AWS_SECRET_ACCESS_KEY}}

    - name: Build Documentation
      run: cargo +nightly doc --no-deps --all --all-features

    - name: Add index file
      run: |
        mkdir host-docs
        echo "<meta http-equiv=\"refresh\" content=\"0; url=topos\">" > target/doc/index.html
        cp -r target/doc/* ./host-docs
    - name: Upload documentation
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: "host-docs/"

  deploy:
    name: Deploy documentation
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
