name: Topos - Docker template

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AWS_SHARED_CREDENTIALS_FILE: "${{ github.workspace }}/.aws/credentials"

on:
  workflow_call:
    inputs:
      # Docker target (test | fmt | lint | topos | etc)
      target:
        required: false
        type: string
        default: topos
      # Rust toolchain version (stable | nightly)
      toolchain_version:
        required: false
        type: string
        default: stable
    outputs:
      tags:
        description: "Docker tags"
        value: ${{ jobs.docker.outputs.tags }}

jobs:
  docker:
    name: Build and push docker image to GitHub Container Registry
    runs-on: ubuntu-latest-16-core
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          short-length: 7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials for cicd-devnet-1 account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ROBOT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ROBOT_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::367397670706:role/CacheBucketAccessRole
          role-session-name: RobotToposware-session
          aws-region: us-east-1
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - name: Add profile credentials to .aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile default
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile default

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          # push only images targeting topos (e.g.: exclude test, lint, etc.)
          push: ${{ inputs.target == 'topos' }}
          target: ${{ inputs.target }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secret-files: |
            "aws=${{ github.workspace }}/.aws/credentials"
          build-args: |
            RUSTUP_TOOLCHAIN=${{ inputs.toolchain_version }}
            SCCACHE_S3_KEY_PREFIX=${{ inputs.target }}
            SCCACHE_BUCKET=cicd-devnet-1-sccache
            SCCACHE_REGION=us-east-1
            RUSTC_WRAPPER=/usr/local/cargo/bin/sccache
